import Head from 'next/head';
import React from 'react'
import MainVisual from './MainVisual';
import Navigation from './Navigation';

interface Props {

}

const Layout: React.FC<Props> = ({children}) => {
  return (
    <div>
      <Head>
        <title>Kanji.com</title>
        <meta charSet="utf-8"/>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <MainVisual />
      {children}
      </main>
      <footer>
       
      </footer>
    </div>
  )
}

export default Layout
